@echo off
echo Checking for processes on port 3000...
netstat -aon | findstr :3000 >nul
if %errorlevel% equ 0 (
    echo Found processes on port 3000, killing them...
    for /f "tokens=5" %%a in ('netstat -aon ^| findstr :3000') do (
        echo Killing process %%a
        taskkill /f /pid %%a 2>nul
    )
    echo Waiting 2 seconds for processes to terminate...
    timeout /t 2 /nobreak >nul
) else (
    echo No processes found on port 3000, starting directly...
)
echo Starting development server...
nest start --watch
